### ISSUE TITLE
[改善]デプロイの自動化

### ISSUE THREAD

**Issue by h-yoshikawa44** [h-yoshikawa44/close-to-2#24]
## 対象環境
本番

## 目的
デプロイを自動化して効率化したい

## 作業内容
- GitHub Pages へのデプロイを GitHub Actions でワークフロー化
 （以前も試みたがうまくいかなったので、再度挑戦する）

**Comment by h-yoshikawa44** [comment]
## ローカルで react-snap が失敗するようになった問題
ビルド後に react-snap を実行するような仕組みにしていたが、内部的に使用している Puppeteer が失敗するようになっていた。
(GitHub Actions では、すでに導入されているのか、このエラーは出なかった）

### 足りないパッケージ
```bash
$ react-snap
Error: Failed to launch chrome!
/mnt/c/Users/ballk/development/my-projects/close-to-2/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXcursor.so.1: cannot open shared object file: No such file or directory


TROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

    at onClose (/mnt/c/Users/ballk/development/my-projects/close-to-2/node_modules/puppeteer/lib/Launcher.js:348:14)
    at Interface.<anonymous> (/mnt/c/Users/ballk/development/my-projects/close-to-2/node_modules/puppeteer/lib/Launcher.js:337:50)
    at Interface.emit (events.js:387:35)
    at Interface.close (readline.js:451:8)
    at Socket.onend (readline.js:224:10)
    at Socket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
libXcursor というパッケージがないと言われているので追加。
```
$ sudo apt install libxcursor-dev
```

同様に以下のパッケージも追加
- libnss3
- libcups（パッケージ名としては libcups2）
- libxss-dev
- libatk1.0-dev
- libatk-bridge2.0-dev
- libpangocairo-1.0
- libgtk-3-dev

### sandbox 問題
```
Error: Failed to launch chrome!
[0808/155836.714631:FATAL:zygote_host_impl_linux.cc(116)] No usable sandbox! Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
```

ここまできて、ふと思ったのが、react-snap の最終更新が2019年だったため、他のライブラリに移行した方が早い気がしてきた。

**Comment by h-yoshikawa44** [comment]
## react-snapshot への移行
[react-ogp](https://github.com/talentlessguy/react-ogp) という比較的新しいライブラリを見かけたが、[react-snapshot](https://github.com/geelen/react-snapshot) の方を使うことにした。
こちらは README に react-snap が非推奨になったとの記述もあり、後継ライブラリとして作られたっぽい？

```
yarn add -D react-snapshot
```
package.json を以下のように修正
```diff
- "build": "react-scripts build"
+ "build": "react-scripts build && react-snapshot"
```
index.js を以下のように修正
```diff
- import ReactDOM from 'react-dom';
+ import { render } from 'react-snapshot';

- ReactDOM.render(
+ render(
    <App/>,
    document.getElementById('root')
  );
```

**Comment by h-yoshikawa44** [comment]
## 自動デプロイ
アクションを使用
```yml
- name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
```

やはりデプロイ自体は成功するものの、真っ白になってしまう現象が起きた。
コンソールには以下のエラーが出ていた。
```
TypeError: Cannot read property 'originalIndex' of undefined
    at Game.js:100
    at dt (Game.js:118)
    at Game.js:150
    at Lu (react-dom.production.min.js:262)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at $o (react-dom.production.min.js:122)
    at Nu (react-dom.production.min.js:261)
    at yu (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```
```
Uncaught TypeError: Cannot read property 'originalIndex' of undefined
    at Game.js:100
    at dt (Game.js:118)
    at Game.js:150
    at Lu (react-dom.production.min.js:262)
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
    at $o (react-dom.production.min.js:122)
    at Nu (react-dom.production.min.js:261)
    at yu (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```

**Comment by h-yoshikawa44** [comment]
## 自動デプロイ時のコミットメッセージ設定修正
v1.0.0 リリースにいれていた、コミットメッセージ設定だと構文エラーになったりでうまく動かず...。
試しながらコミットしたので、コミットが汚くなってしまったが最終的には以下でいけた。

どうもダブルクォートの部分は別にエスケープしなくてよかったらしい。
（firebase hosting にデプロイ時はエスケープしていたし、エスケープしないと変数が展開されずに文字列認識されると思ってた）
```
- name: Build & Deploy to GitHub Pages
   run: |
     git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
     yarn deploy -u "github-actions-bot <support+actions@github.com>" -m "${{ github.event.head_commit.message }}"
   env:
     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
